### ISSUE TITLE
What is the name of the font?

### ISSUE THREAD

**Issue by KermanGreem** [benbusby/earthbound-themes#12]
What is the font used in the presentation of your theme?
<img width="683" alt="Screenshot 2021-12-05 at 16 02 10" src="https://user-images.githubusercontent.com/85343923/144752030-6cbac0e5-126d-4fd4-9c23-c93a2a16a37f.png">

**Comment by benbusby** [comment]
It's a font that I made called [Anomaly Mono](https://github.com/benbusby/anomaly-mono).

**Comment by KermanGreem** [comment]
Thanks a lot, I have been searching for this font for a while now!
