### ISSUE TITLE
Syntax theme not changing in Atom 1.53.0 on Windows 8.1 or 10

### ISSUE THREAD

**Issue by nabontra** [benbusby/earthbound-themes#6]
I have installed this theme in fresh installs of Atom 1.53.0 on a Windows 8.1 and Windows 10 OS. The syntax theme is installed via the Atom installer and shows that it is selected and changing via config.cson, but the file editing window is unaffected. Deprecation cop does show some Deprecated Selectors, but suggests that they are being automatically corrected. I'm new to Atom, so apologies if I have missed a requirement. Are there dependencies/packages for this syntax theme that I would need on a fresh Atom install?

Thanks for the beautiful themes!

**Comment by benbusby** [comment]
Thanks for the report! I just pushed a fix that should address this, could you update the theme package to the latest version (`v1.0.1`) and let me know if that's working for you? 

As a side note, the theme switcher also requires Atom to be reloaded (`Ctrl-Alt-R` on Windows I think) each time a new sub-theme is selected in the theme settings dropdown menu (not the main Atom syntax theme switcher).

<img width="501" alt="Screen Shot 2020-12-31 at 2 37 18 PM" src="https://user-images.githubusercontent.com/33362396/103423679-ec247080-4b75-11eb-9d39-8d85ee033619.png">

Apologies if you knew that already -- it's a behavior that I often forget as a non-Atom user, so I figured I'd bring it up.

**Comment by nabontra** [comment]
I have just updated to the new version and can confirm that it is now working! Previously, the reloading of Atom was not showing any changes as well (I just realized that I left that note out of my report). Thank you for the quick fix!
