### ISSUE TITLE
Font Used In Screenshots

### ISSUE THREAD

**Issue by Smeeba** [benbusby/earthbound-themes#7]
Hey, I was just wonder what font was used in the screenshots. Its nowhere on the page and I was really curious what its called/if I could have a link to it.

**Comment by benbusby** [comment]
Hey, thanks! The font is actually a font I designed called Anomaly Mono, available here: https://github.com/benbusby/anomaly-mono.

**Comment by Smeeba** [comment]
Thank you! I really like the look of it, great work!
