### ISSUE TITLE
Sublime 4 issues

### ISSUE THREAD

**Issue by rojakzym** [benbusby/earthbound-themes#8]
any part with plain text isnt colored. 
![imagen](https://user-images.githubusercontent.com/1781797/120399596-f3f16800-c301-11eb-805a-81721ae0380f.png)
![imagen](https://user-images.githubusercontent.com/1781797/120399598-f6ec5880-c301-11eb-90a1-49ed03ad2df6.png)

**Comment by benbusby** [comment]
Thanks for bringing this to my attention! A fix has been pushed and should be available through the Sublime package manager soon.
